/**
 * AI Tool Schemas for Claude Agent SDK Sidecar
 *
 * Auto-generated from TypeSpec @aiTool decorators
 * Do not edit this file directly
 *
 * Source: typespec/apis/*.tsp with @aiTool decorators
 * Generated: 2026-04-03T06:42:25.774Z
 */

// Standalone enums (no external imports)
export type AIToolCategory = 'catalog' | 'query' | 'job' | 'branch' | 'operational' | 'admin' | 'lineage' | 'import' | 'connection' | 'workflow';
export type AIToolTier = 'mvp' | 'phase2' | 'phase3';
export type AsyncResultType = 'query' | 'job_run' | 'workflow';
export type AIToolMode = 'cloud' | 'local' | 'onpremise' | 'web';

export interface BedrockToolSchema {
  name: string;
  description: string;
  inputSchema: {
    json: {
      type: 'object';
      properties: Record<string, JsonSchemaProperty>;
      required?: string[];
    };
  };
}

export interface JsonSchemaProperty {
  type?: string;  // Optional - some props only have $ref
  description?: string;
  enum?: string[];
  items?: JsonSchemaProperty | Record<string, unknown>;
  properties?: Record<string, JsonSchemaProperty>;
  required?: string[];
  default?: unknown;
  additionalProperties?: boolean | Record<string, unknown>;
  format?: string;
  minimum?: number;
  maximum?: number;
  $schema?: string;
  $id?: string;
  $ref?: string;
}

export interface AIToolMetadata extends BedrockToolSchema {
  category: AIToolCategory;
  requiresConfirmation: boolean;
  tier: AIToolTier;
  httpMethod: string;
  route: string;
  /** Response field containing async operation ID (e.g., "queryExecutionId") */
  asyncResultField?: string;
  /** Type of async operation for polling */
  asyncResultType?: AsyncResultType;
  /** Primary array field in response for smart trimming (e.g., "tables", "rows") */
  responseArrayField?: string;
  /** Operating modes where this tool is available (undefined = all modes) */
  modes?: AIToolMode[];
}

export const AI_TOOLS: AIToolMetadata[] = [
  {
    name: 'create_command',
    description: 'Create a new slash command (reusable prompt)',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/ai/commands',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "name": {
                              "type": "string",
                              "description": "name parameter"
                      },
                      "content": {
                              "type": "string",
                              "description": "content parameter"
                      }
              },
              "required": [
                      "name",
                      "content"
              ]
      },
    },
    modes: ['web'],
  },
  {
    name: 'create_skill',
    description: 'Create a new reusable skill (prompt/instruction) that persists across sessions',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/ai/skills',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "name": {
                              "type": "string",
                              "description": "name parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      },
                      "content": {
                              "type": "string",
                              "description": "content parameter"
                      }
              },
              "required": [
                      "name",
                      "description",
                      "content"
              ]
      },
    },
    modes: ['web'],
  },
  {
    name: 'delete_command',
    description: 'Delete a command by name',
    category: 'catalog',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'DELETE',
    route: '/ai/commands/{name}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "name": {
                              "type": "string",
                              "description": "name parameter"
                      }
              },
              "required": [
                      "name"
              ]
      },
    },
    modes: ['web'],
  },
  {
    name: 'delete_skill',
    description: 'Delete a skill by name',
    category: 'catalog',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'DELETE',
    route: '/ai/skills/{name}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "name": {
                              "type": "string",
                              "description": "name parameter"
                      }
              },
              "required": [
                      "name"
              ]
      },
    },
    modes: ['web'],
  },
  {
    name: 'get_memory',
    description: 'Get persistent memory content (notes that survive across sessions)',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/ai/memory',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {}
      },
    },
    modes: ['web'],
  },
  {
    name: 'get_skill',
    description: 'Get a skill\'s full content by name',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/ai/skills/{name}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "name": {
                              "type": "string",
                              "description": "name parameter"
                      }
              },
              "required": [
                      "name"
              ]
      },
    },
    modes: ['web'],
  },
  {
    name: 'get_table_dependencies',
    description: 'Get table dependencies for lineage analysis',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/tables/{database}/{table}/dependencies',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "table": {
                              "type": "string",
                              "description": "table parameter"
                      }
              },
              "required": [
                      "database",
                      "table"
              ]
      },
    },
    modes: ['cloud'],
  },
  {
    name: 'get_table_info',
    description: 'Get complete table information including schema, dependencies, and metadata',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/tables/{database}/{table}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "table": {
                              "type": "string",
                              "description": "table parameter"
                      },
                      "branch": {
                              "type": "string",
                              "description": "branch parameter"
                      },
                      "includeSchema": {
                              "type": "boolean",
                              "description": "includeSchema parameter"
                      },
                      "includeMetadata": {
                              "type": "boolean",
                              "description": "includeMetadata parameter"
                      }
              },
              "required": [
                      "database",
                      "table"
              ]
      },
    },
  },
  {
    name: 'get_table_schema',
    description: 'Get table schema including columns, partitions, and primary keys',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/tables/{database}/{table}/schema',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "table": {
                              "type": "string",
                              "description": "table parameter"
                      }
              },
              "required": [
                      "database",
                      "table"
              ]
      },
    },
  },
  {
    name: 'list_commands',
    description: 'List all user-defined slash commands',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/ai/commands',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {}
      },
    },
    responseArrayField: 'commands',
    modes: ['web'],
  },
  {
    name: 'list_databases',
    description: 'List all databases in the catalog',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/databases',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "pageSize": {
                              "type": "number",
                              "description": "pageSize parameter"
                      },
                      "nextToken": {
                              "type": "string",
                              "description": "nextToken parameter"
                      }
              }
      },
    },
    responseArrayField: 'databases',
  },
  {
    name: 'list_skills',
    description: 'List all user-defined skills (reusable prompts/instructions)',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/ai/skills',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {}
      },
    },
    responseArrayField: 'skills',
    modes: ['web'],
  },
  {
    name: 'list_tables',
    description: 'List all tables in a database',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/tables',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "tableType": {
                              "type": "string",
                              "description": "tableType parameter"
                      },
                      "pageSize": {
                              "type": "number",
                              "description": "pageSize parameter"
                      },
                      "nextToken": {
                              "type": "string",
                              "description": "nextToken parameter"
                      },
                      "includeSchema": {
                              "type": "boolean",
                              "description": "includeSchema parameter"
                      },
                      "view": {
                              "type": "string",
                              "description": "view parameter"
                      }
              },
              "required": [
                      "database"
              ]
      },
    },
    responseArrayField: 'tables',
  },
  {
    name: 'search_catalog',
    description: 'Search catalog for databases, tables, and columns. Supports fuzzy matching - adjust threshold (0-1, lower=stricter) and distance if no results found.',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/search',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "searchQuery": {
                              "type": "string",
                              "description": "searchQuery parameter"
                      },
                      "searchType": {
                              "type": "string",
                              "enum": [
                                      "all",
                                      "database",
                                      "table",
                                      "column"
                              ],
                              "description": "searchType parameter"
                      },
                      "limit": {
                              "type": "number",
                              "description": "limit parameter"
                      },
                      "threshold": {
                              "type": "number",
                              "description": "threshold parameter"
                      },
                      "distance": {
                              "type": "number",
                              "description": "distance parameter"
                      }
              },
              "required": [
                      "searchQuery"
              ]
      },
    },
    responseArrayField: 'results',
  },
  {
    name: 'show_lineage',
    description: 'Display a lineage visualization inline in the chat. Shows table dependencies as an interactive graph. Pass database and tableName to fetch and display the lineage for that table.',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: '',
    route: '',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "Database name containing the table"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "Table name to show lineage for"
                      },
                      "branch": {
                              "type": "string",
                              "description": "Branch name (optional, defaults to main)"
                      },
                      "direction": {
                              "type": "string",
                              "enum": [
                                      "upstream",
                                      "downstream",
                                      "both"
                              ],
                              "description": "Lineage direction: upstream (sources), downstream (dependents), or both (default)"
                      }
              },
              "required": [
                      "database",
                      "tableName"
              ]
      },
    },
  },
  {
    name: 'update_command',
    description: 'Update an existing command\'s content',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'PUT',
    route: '/ai/commands/{name}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "name": {
                              "type": "string",
                              "description": "name parameter"
                      },
                      "content": {
                              "type": "string",
                              "description": "content parameter"
                      }
              },
              "required": [
                      "name",
                      "content"
              ]
      },
    },
    modes: ['web'],
  },
  {
    name: 'update_memory',
    description: 'Update persistent memory content (notes that survive across sessions)',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'PUT',
    route: '/ai/memory',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "content": {
                              "type": "string",
                              "description": "content parameter"
                      }
              },
              "required": [
                      "content"
              ]
      },
    },
    modes: ['web'],
  },
  {
    name: 'update_skill',
    description: 'Update an existing skill\'s content or description',
    category: 'catalog',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'PUT',
    route: '/ai/skills/{name}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "name": {
                              "type": "string",
                              "description": "name parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      },
                      "content": {
                              "type": "string",
                              "description": "content parameter"
                      }
              },
              "required": [
                      "name",
                      "content"
              ]
      },
    },
    modes: ['web'],
  },
  {
    name: 'create_connection',
    description: 'Create a new database connection (PostgreSQL or Snowflake). Credentials are stored securely in AWS Secrets Manager.',
    category: 'connection',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/connections',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {}
      },
    },
  },
  {
    name: 'detect_connection_schema',
    description: 'Detect schema and sample data for a table (PostgreSQL or Snowflake) via saved connection',
    category: 'connection',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/connections/{connectionId}/schema',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "connectionId": {
                              "type": "string",
                              "description": "connectionId parameter"
                      },
                      "schema": {
                              "type": "string",
                              "description": "schema parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "sampleSize": {
                              "type": "number",
                              "description": "sampleSize parameter"
                      }
              },
              "required": [
                      "connectionId",
                      "schema",
                      "tableName"
              ]
      },
    },
  },
  {
    name: 'list_connection_tables',
    description: 'List all tables in a database (PostgreSQL or Snowflake) via a saved connection',
    category: 'connection',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/connections/{connectionId}/tables',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "connectionId": {
                              "type": "string",
                              "description": "connectionId parameter"
                      },
                      "schema": {
                              "type": "string",
                              "description": "schema parameter"
                      }
              },
              "required": [
                      "connectionId"
              ]
      },
    },
  },
  {
    name: 'list_connections',
    description: 'List all saved database connections',
    category: 'connection',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/connections',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {}
      },
    },
  },
  {
    name: 'query_external_connection',
    description: 'Execute a read-only SQL query against a saved database connection (PostgreSQL or Snowflake). Returns up to maxRows rows. Prefer maxRows instead of LIMIT/TOP/FETCH. For Snowflake, inspect schema first and quote lowercase identifiers exactly.',
    category: 'connection',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/connections/{connectionId}/query',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "connectionId": {
                              "type": "string",
                              "description": "connectionId parameter"
                      },
                      "query": {
                              "type": "string",
                              "description": "query parameter"
                      },
                      "maxRows": {
                              "type": "number",
                              "description": "maxRows parameter"
                      },
                      "timeoutSeconds": {
                              "type": "number",
                              "description": "timeoutSeconds parameter"
                      }
              },
              "required": [
                      "connectionId",
                      "query"
              ]
      },
    },
  },
  {
    name: 'test_connection',
    description: 'Test a database connection (PostgreSQL or Snowflake) to verify connectivity before saving',
    category: 'connection',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/connections/test',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {}
      },
    },
  },
  {
    name: 'detect_glue_schema',
    description: 'Detect schema from a Glue catalog table. Use before import_from_glue to preview the table structure.',
    category: 'import',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/import/detect-glue',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "sourceDatabase": {
                              "type": "string",
                              "description": "sourceDatabase parameter"
                      },
                      "sourceTable": {
                              "type": "string",
                              "description": "sourceTable parameter"
                      },
                      "sourceAccountId": {
                              "type": "string",
                              "description": "sourceAccountId parameter"
                      }
              },
              "required": [
                      "sourceDatabase",
                      "sourceTable"
              ]
      },
    },
    modes: ['cloud'],
  },
  {
    name: 'detect_s3_schema',
    description: 'Detect schema, format, and partitions from S3 data. Use before import_from_s3 to preview what will be imported.',
    category: 'import',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/import/detect',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "s3Location": {
                              "type": "string",
                              "description": "s3Location parameter"
                      },
                      "format": {
                              "type": "string",
                              "enum": [
                                      "parquet",
                                      "csv",
                                      "json",
                                      "avro",
                                      "orc"
                              ],
                              "description": "format parameter"
                      },
                      "sampleSize": {
                              "type": "number",
                              "description": "sampleSize parameter"
                      }
              },
              "required": [
                      "s3Location"
              ]
      },
    },
    modes: ['cloud'],
  },
  {
    name: 'import_from_glue',
    description: 'Import a table from AWS Glue catalog by creating a resource link. No data copy - queries go directly to source.',
    category: 'import',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/import/glue',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "sourceDatabase": {
                              "type": "string",
                              "description": "sourceDatabase parameter"
                      },
                      "sourceTable": {
                              "type": "string",
                              "description": "sourceTable parameter"
                      },
                      "sourceAccountId": {
                              "type": "string",
                              "description": "sourceAccountId parameter"
                      },
                      "crawlerSchedule": {
                              "$schema": "https://json-schema.org/draft/2020-12/schema",
                              "$id": "CrawlerSchedule.yaml",
                              "type": "object",
                              "properties": {
                                      "type": {
                                              "$ref": "CrawlerScheduleType.yaml",
                                              "description": "Schedule type (hourly, daily, weekly, custom)"
                                      },
                                      "cronExpression": {
                                              "type": "string",
                                              "description": "Custom cron expression (required if type is 'custom')"
                                      }
                              },
                              "required": [
                                      "type"
                              ],
                              "description": "crawlerSchedule parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      }
              },
              "required": [
                      "database",
                      "tableName",
                      "sourceDatabase",
                      "sourceTable",
                      "crawlerSchedule"
              ]
      },
    },
    asyncResultField: 'executionArn',
    asyncResultType: 'workflow',
    modes: ['cloud'],
  },
  {
    name: 'import_from_paste',
    description: 'Import tabular data directly into a managed Iceberg table. Provide schema and rows as a 2D array.',
    category: 'import',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/import/paste',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "schema": {
                              "type": "array",
                              "items": {
                                      "$schema": "https://json-schema.org/draft/2020-12/schema",
                                      "$id": "Column.yaml",
                                      "type": "object",
                                      "properties": {
                                              "name": {
                                                      "type": "string",
                                                      "description": "Column name"
                                              },
                                              "dataType": {
                                                      "type": "string",
                                                      "description": "Data type"
                                              },
                                              "nullable": {
                                                      "type": "boolean",
                                                      "description": "Whether column can contain nulls"
                                              },
                                              "description": {
                                                      "type": "string",
                                                      "description": "Human-readable description"
                                              },
                                              "isPartition": {
                                                      "type": "boolean",
                                                      "description": "Whether this is a partition column"
                                              },
                                              "isPrimaryKey": {
                                                      "type": "boolean",
                                                      "description": "Whether this is part of primary key"
                                              },
                                              "defaultValue": {
                                                      "type": "string",
                                                      "description": "Default value expression"
                                              },
                                              "metadata": {
                                                      "$ref": "#/$defs/RecordUnknown",
                                                      "description": "Column-level metadata"
                                              },
                                              "precision": {
                                                      "type": "integer",
                                                      "minimum": -2147483648,
                                                      "maximum": 2147483647,
                                                      "description": "For decimal types: precision"
                                              },
                                              "scale": {
                                                      "type": "integer",
                                                      "minimum": -2147483648,
                                                      "maximum": 2147483647,
                                                      "description": "For decimal types: scale"
                                              },
                                              "elementType": {
                                                      "type": "string",
                                                      "description": "For array/map types: element type"
                                              },
                                              "nestedFields": {
                                                      "type": "array",
                                                      "items": {
                                                              "$ref": "Column.yaml"
                                                      },
                                                      "description": "For struct types: nested fields"
                                              }
                                      },
                                      "required": [
                                              "name",
                                              "dataType",
                                              "nullable"
                                      ],
                                      "description": "Column definition for table schema",
                                      "$defs": {
                                              "RecordUnknown": {
                                                      "type": "object",
                                                      "properties": {},
                                                      "additionalProperties": {}
                                              }
                                      }
                              },
                              "description": "schema parameter"
                      },
                      "rows": {
                              "type": "array",
                              "items": {
                                      "type": "array",
                                      "items": {
                                              "type": "string"
                                      }
                              },
                              "description": "rows parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      }
              },
              "required": [
                      "database",
                      "tableName",
                      "schema",
                      "rows"
              ]
      },
    },
    asyncResultField: 'executionArn',
    asyncResultType: 'workflow',
  },
  {
    name: 'import_from_postgres',
    description: 'Import a PostgreSQL table into a managed Iceberg table. Requires a saved connectionId.',
    category: 'import',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/import/postgres',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "connectionId": {
                              "type": "string",
                              "description": "connectionId parameter"
                      },
                      "sourceSchema": {
                              "type": "string",
                              "description": "sourceSchema parameter"
                      },
                      "sourceTable": {
                              "type": "string",
                              "description": "sourceTable parameter"
                      },
                      "postgresConfig": {
                              "$schema": "https://json-schema.org/draft/2020-12/schema",
                              "$id": "PostgresImportConfig.yaml",
                              "type": "object",
                              "properties": {
                                      "connectionId": {
                                              "type": "string",
                                              "description": "Connection ID referencing dvc_connections table"
                                      },
                                      "sourceSchema": {
                                              "type": "string",
                                              "description": "Source schema name (default: public)"
                                      },
                                      "sourceTable": {
                                              "type": "string",
                                              "description": "Source table name"
                                      },
                                      "partitionColumn": {
                                              "type": "string",
                                              "description": "Partition column for parallel JDBC reads (optional)"
                                      },
                                      "partitionStrategy": {
                                              "type": "string",
                                              "default": "auto",
                                              "description": "Partition strategy for JDBC reads\n- \"auto\": choose column-based if possible, else predicate-based\n- \"column\": use partitionColumn + bounds\n- \"predicates\": use custom predicates array\n- \"single\": no partitioning"
                                      },
                                      "numPartitions": {
                                              "type": "integer",
                                              "minimum": -2147483648,
                                              "maximum": 2147483647,
                                              "default": 4,
                                              "description": "Number of partitions for parallel reads (default: 4)"
                                      },
                                      "lowerBound": {
                                              "type": "string",
                                              "description": "Lower bound for partition column"
                                      },
                                      "upperBound": {
                                              "type": "string",
                                              "description": "Upper bound for partition column"
                                      },
                                      "predicates": {
                                              "type": "array",
                                              "items": {
                                                      "type": "string"
                                              },
                                              "description": "Predicate-based partitioning for non-numeric keys\nExample: [\"mod(hashtext(id::text), 8) = 0\", ...]"
                                      },
                                      "fetchSize": {
                                              "type": "integer",
                                              "minimum": -2147483648,
                                              "maximum": 2147483647,
                                              "default": 10000,
                                              "description": "Fetch size for JDBC result sets (default: 10000)"
                                      },
                                      "lastSyncAt": {
                                              "type": "string",
                                              "format": "date-time",
                                              "description": "Last sync timestamp"
                                      },
                                      "lastSyncSnapshotId": {
                                              "type": "string",
                                              "description": "Last sync snapshot ID"
                                      },
                                      "syncSchedule": {
                                              "type": "string",
                                              "description": "Sync schedule (cron expression)"
                                      },
                                      "refreshQueryMode": {
                                              "type": "string",
                                              "default": "full",
                                              "description": "Query refresh mode: \"full\" (Phase 1 only)"
                                      },
                                      "ingestionMode": {
                                              "type": "string",
                                              "default": "replace",
                                              "description": "Ingestion mode: \"replace\" | \"merge\""
                                      },
                                      "primaryKeys": {
                                              "type": "array",
                                              "items": {
                                                      "type": "string"
                                              },
                                              "description": "Primary key columns for merge mode"
                                      },
                                      "primaryKeysDerived": {
                                              "type": "boolean",
                                              "description": "Whether primary keys were auto-derived from PG constraints"
                                      },
                                      "scheduleArn": {
                                              "type": "string",
                                              "description": "Schedule ARN from EventBridge Scheduler"
                                      },
                                      "lastRunStatus": {
                                              "type": "string",
                                              "description": "Last run status"
                                      },
                                      "lastRunError": {
                                              "type": "string",
                                              "description": "Last run error message"
                                      },
                                      "nextScheduledRun": {
                                              "type": "string",
                                              "format": "date-time",
                                              "description": "Next scheduled run (ISO timestamp)"
                                      },
                                      "importStrategy": {
                                              "type": "string",
                                              "default": "jdbc",
                                              "description": "Import strategy: \"jdbc\" | \"dump\" | \"auto\""
                                      },
                                      "retainLastSnapshots": {
                                              "type": "integer",
                                              "minimum": -2147483648,
                                              "maximum": 2147483647,
                                              "description": "Number of Iceberg snapshots to retain during scheduled expiration"
                                      },
                                      "dumpConfig": {
                                              "$ref": "PostgresDumpConfig.yaml",
                                              "description": "Dump-based import configuration (used when importStrategy = \"dump\")"
                                      }
                              },
                              "required": [
                                      "connectionId",
                                      "sourceSchema",
                                      "sourceTable"
                              ],
                              "description": "postgresConfig parameter"
                      },
                      "refreshRun": {
                              "type": "boolean",
                              "description": "refreshRun parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      }
              },
              "required": [
                      "database",
                      "tableName",
                      "connectionId",
                      "sourceTable"
              ]
      },
    },
    asyncResultField: 'executionArn',
    asyncResultType: 'workflow',
    modes: ['cloud'],
  },
  {
    name: 'import_from_s3',
    description: 'Import data from S3 location as an external table with automatic schema detection via Glue Crawler. Returns executionArn for progress tracking.',
    category: 'import',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/import/s3',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "s3Location": {
                              "type": "string",
                              "description": "s3Location parameter"
                      },
                      "format": {
                              "type": "string",
                              "enum": [
                                      "parquet",
                                      "csv",
                                      "json",
                                      "avro",
                                      "orc"
                              ],
                              "description": "format parameter"
                      },
                      "schema": {
                              "type": "array",
                              "items": {
                                      "$schema": "https://json-schema.org/draft/2020-12/schema",
                                      "$id": "Column.yaml",
                                      "type": "object",
                                      "properties": {
                                              "name": {
                                                      "type": "string",
                                                      "description": "Column name"
                                              },
                                              "dataType": {
                                                      "type": "string",
                                                      "description": "Data type"
                                              },
                                              "nullable": {
                                                      "type": "boolean",
                                                      "description": "Whether column can contain nulls"
                                              },
                                              "description": {
                                                      "type": "string",
                                                      "description": "Human-readable description"
                                              },
                                              "isPartition": {
                                                      "type": "boolean",
                                                      "description": "Whether this is a partition column"
                                              },
                                              "isPrimaryKey": {
                                                      "type": "boolean",
                                                      "description": "Whether this is part of primary key"
                                              },
                                              "defaultValue": {
                                                      "type": "string",
                                                      "description": "Default value expression"
                                              },
                                              "metadata": {
                                                      "$ref": "#/$defs/RecordUnknown",
                                                      "description": "Column-level metadata"
                                              },
                                              "precision": {
                                                      "type": "integer",
                                                      "minimum": -2147483648,
                                                      "maximum": 2147483647,
                                                      "description": "For decimal types: precision"
                                              },
                                              "scale": {
                                                      "type": "integer",
                                                      "minimum": -2147483648,
                                                      "maximum": 2147483647,
                                                      "description": "For decimal types: scale"
                                              },
                                              "elementType": {
                                                      "type": "string",
                                                      "description": "For array/map types: element type"
                                              },
                                              "nestedFields": {
                                                      "type": "array",
                                                      "items": {
                                                              "$ref": "Column.yaml"
                                                      },
                                                      "description": "For struct types: nested fields"
                                              }
                                      },
                                      "required": [
                                              "name",
                                              "dataType",
                                              "nullable"
                                      ],
                                      "description": "Column definition for table schema",
                                      "$defs": {
                                              "RecordUnknown": {
                                                      "type": "object",
                                                      "properties": {},
                                                      "additionalProperties": {}
                                              }
                                      }
                              },
                              "description": "schema parameter"
                      },
                      "partitionColumns": {
                              "type": "array",
                              "items": {
                                      "type": "string"
                              },
                              "description": "partitionColumns parameter"
                      },
                      "crawlerSchedule": {
                              "$schema": "https://json-schema.org/draft/2020-12/schema",
                              "$id": "CrawlerSchedule.yaml",
                              "type": "object",
                              "properties": {
                                      "type": {
                                              "$ref": "CrawlerScheduleType.yaml",
                                              "description": "Schedule type (hourly, daily, weekly, custom)"
                                      },
                                      "cronExpression": {
                                              "type": "string",
                                              "description": "Custom cron expression (required if type is 'custom')"
                                      }
                              },
                              "required": [
                                      "type"
                              ],
                              "description": "crawlerSchedule parameter"
                      },
                      "csvOptions": {
                              "$schema": "https://json-schema.org/draft/2020-12/schema",
                              "$id": "CsvOptions.yaml",
                              "type": "object",
                              "properties": {
                                      "delimiter": {
                                              "type": "string",
                                              "default": ",",
                                              "description": "Field delimiter (default: ,)"
                                      },
                                      "hasHeader": {
                                              "type": "boolean",
                                              "default": true,
                                              "description": "Whether first row is header (default: true)"
                                      },
                                      "quoteChar": {
                                              "type": "string",
                                              "default": "\"",
                                              "description": "Quote character (default: \")"
                                      }
                              },
                              "description": "csvOptions parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      }
              },
              "required": [
                      "database",
                      "tableName",
                      "s3Location",
                      "format",
                      "crawlerSchedule"
              ]
      },
    },
    asyncResultField: 'executionArn',
    asyncResultType: 'workflow',
    modes: ['cloud'],
  },
  {
    name: 'import_from_snowflake',
    description: 'Import a Snowflake table into a managed Iceberg table. Requires a saved connectionId.',
    category: 'import',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/import/snowflake',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "connectionId": {
                              "type": "string",
                              "description": "connectionId parameter"
                      },
                      "sourceSchema": {
                              "type": "string",
                              "description": "sourceSchema parameter"
                      },
                      "sourceTable": {
                              "type": "string",
                              "description": "sourceTable parameter"
                      },
                      "snowflakeConfig": {
                              "$schema": "https://json-schema.org/draft/2020-12/schema",
                              "$id": "SnowflakeImportConfig.yaml",
                              "type": "object",
                              "properties": {
                                      "connectionId": {
                                              "type": "string",
                                              "description": "Connection ID referencing dvc_connections table"
                                      },
                                      "sourceSchema": {
                                              "type": "string",
                                              "description": "Source schema name (default: PUBLIC)"
                                      },
                                      "sourceTable": {
                                              "type": "string",
                                              "description": "Source table name"
                                      },
                                      "partitionColumn": {
                                              "type": "string",
                                              "description": "Partition column for parallel JDBC reads (optional)"
                                      },
                                      "partitionStrategy": {
                                              "type": "string",
                                              "default": "auto",
                                              "description": "Partition strategy for JDBC reads\n- \"auto\": choose column-based if possible, else single\n- \"column\": use partitionColumn + bounds\n- \"single\": no partitioning"
                                      },
                                      "numPartitions": {
                                              "type": "integer",
                                              "minimum": -2147483648,
                                              "maximum": 2147483647,
                                              "default": 4,
                                              "description": "Number of partitions for parallel reads (default: 4)"
                                      },
                                      "lowerBound": {
                                              "type": "string",
                                              "description": "Lower bound for partition column"
                                      },
                                      "upperBound": {
                                              "type": "string",
                                              "description": "Upper bound for partition column"
                                      },
                                      "fetchSize": {
                                              "type": "integer",
                                              "minimum": -2147483648,
                                              "maximum": 2147483647,
                                              "default": 10000,
                                              "description": "Fetch size for JDBC result sets (default: 10000)"
                                      },
                                      "lastSyncAt": {
                                              "type": "string",
                                              "format": "date-time",
                                              "description": "Last sync timestamp"
                                      },
                                      "lastSyncSnapshotId": {
                                              "type": "string",
                                              "description": "Last sync snapshot ID"
                                      },
                                      "syncSchedule": {
                                              "type": "string",
                                              "description": "Sync schedule (cron expression)"
                                      },
                                      "refreshQueryMode": {
                                              "type": "string",
                                              "default": "full",
                                              "description": "Query refresh mode: \"full\" (Phase 1 only)"
                                      },
                                      "ingestionMode": {
                                              "type": "string",
                                              "default": "replace",
                                              "description": "Ingestion mode: \"replace\" | \"merge\""
                                      },
                                      "primaryKeys": {
                                              "type": "array",
                                              "items": {
                                                      "type": "string"
                                              },
                                              "description": "Primary key columns for merge mode"
                                      },
                                      "primaryKeysDerived": {
                                              "type": "boolean",
                                              "description": "Whether primary keys were auto-derived from Snowflake constraints"
                                      },
                                      "scheduleArn": {
                                              "type": "string",
                                              "description": "Schedule ARN from EventBridge Scheduler"
                                      },
                                      "lastRunStatus": {
                                              "type": "string",
                                              "description": "Last run status"
                                      },
                                      "lastRunError": {
                                              "type": "string",
                                              "description": "Last run error message"
                                      },
                                      "nextScheduledRun": {
                                              "type": "string",
                                              "format": "date-time",
                                              "description": "Next scheduled run (ISO timestamp)"
                                      },
                                      "importStrategy": {
                                              "type": "string",
                                              "default": "jdbc",
                                              "description": "Import strategy: \"jdbc\" (Phase 1)"
                                      },
                                      "retainLastSnapshots": {
                                              "type": "integer",
                                              "minimum": -2147483648,
                                              "maximum": 2147483647,
                                              "description": "Number of Iceberg snapshots to retain during scheduled expiration"
                                      }
                              },
                              "required": [
                                      "connectionId",
                                      "sourceSchema",
                                      "sourceTable"
                              ],
                              "description": "snowflakeConfig parameter"
                      },
                      "refreshRun": {
                              "type": "boolean",
                              "description": "refreshRun parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      }
              },
              "required": [
                      "database",
                      "tableName",
                      "connectionId",
                      "sourceTable"
              ]
      },
    },
    asyncResultField: 'executionArn',
    asyncResultType: 'workflow',
    modes: ['cloud'],
  },
  {
    name: 'get_job_run_dependencies',
    description: 'Get dependency completeness status for a job run',
    category: 'job',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/jobs/{jobRunId}/dependencies',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "jobRunId": {
                              "type": "string",
                              "description": "jobRunId parameter"
                      },
                      "table": {
                              "type": "string",
                              "description": "table parameter"
                      }
              },
              "required": [
                      "jobRunId",
                      "table"
              ]
      },
    },
    modes: ['cloud'],
  },
  {
    name: 'get_job_run_status',
    description: 'Get job run status and details',
    category: 'job',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/jobs/{jobRunId}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "jobRunId": {
                              "type": "string",
                              "description": "jobRunId parameter"
                      },
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "branch": {
                              "type": "string",
                              "description": "branch parameter"
                      }
              },
              "required": [
                      "jobRunId",
                      "database",
                      "tableName"
              ]
      },
    },
    modes: ['cloud'],
  },
  {
    name: 'list_job_runs',
    description: 'List job runs for a table with filtering options',
    category: 'job',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/jobs',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "Database name containing the table"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "Table name to list job runs for"
                      },
                      "branch": {
                              "type": "string",
                              "description": "branch parameter"
                      },
                      "status": {
                              "type": "string",
                              "description": "status parameter"
                      },
                      "pageSize": {
                              "type": "number",
                              "description": "pageSize parameter"
                      },
                      "nextToken": {
                              "type": "string",
                              "description": "nextToken parameter"
                      }
              },
              "required": [
                      "database",
                      "tableName"
              ]
      },
    },
    responseArrayField: 'jobRuns',
    modes: ['cloud'],
  },
  {
    name: 'trigger_job_run',
    description: 'Trigger a job run for a table',
    category: 'job',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/jobs',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "branch": {
                              "type": "string",
                              "description": "branch parameter"
                      },
                      "parameters": {
                              "type": "object",
                              "additionalProperties": true,
                              "description": "parameters parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      }
              },
              "required": [
                      "database",
                      "tableName"
              ]
      },
    },
    asyncResultField: 'jobRunId',
    asyncResultType: 'job_run',
    modes: ['cloud'],
  },
  {
    name: 'get_snapshot_lineage',
    description: 'Get snapshot-level lineage: find all job runs and tables that consumed a specific snapshot',
    category: 'lineage',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/databases/{database}/tables/{table}/lineage/impact',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "table": {
                              "type": "string",
                              "description": "table parameter"
                      },
                      "snapshotId": {
                              "type": "string",
                              "description": "snapshotId parameter"
                      },
                      "branch": {
                              "type": "string",
                              "description": "branch parameter"
                      }
              },
              "required": [
                      "database",
                      "table",
                      "snapshotId"
              ]
      },
    },
    modes: ['cloud'],
  },
  {
    name: 'get_table_lineage',
    description: 'Get table-level lineage: upstream dependencies and downstream dependents for a table',
    category: 'lineage',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/databases/{database}/tables/{table}/lineage/trace',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "table": {
                              "type": "string",
                              "description": "table parameter"
                      },
                      "branch": {
                              "type": "string",
                              "description": "branch parameter"
                      },
                      "direction": {
                              "type": "string",
                              "enum": [
                                      "upstream",
                                      "downstream",
                                      "both"
                              ],
                              "description": "direction parameter"
                      },
                      "depth": {
                              "type": "number",
                              "description": "depth parameter"
                      },
                      "includeActual": {
                              "type": "boolean",
                              "description": "includeActual parameter"
                      }
              },
              "required": [
                      "database",
                      "table"
              ]
      },
    },
    responseArrayField: 'lineage',
    modes: ['cloud'],
  },
  {
    name: 'get_rollback_impact',
    description: 'Get rollback impact analysis showing affected tables and cascades',
    category: 'operational',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/rollback/{rollbackId}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "rollbackId": {
                              "type": "string",
                              "description": "rollbackId parameter"
                      },
                      "includeJobRuns": {
                              "type": "boolean",
                              "description": "includeJobRuns parameter"
                      },
                      "includeCompleteness": {
                              "type": "boolean",
                              "description": "includeCompleteness parameter"
                      },
                      "maxDepth": {
                              "type": "number",
                              "description": "maxDepth parameter"
                      }
              },
              "required": [
                      "rollbackId"
              ]
      },
    },
    modes: ['cloud'],
  },
  {
    name: 'rollback_table',
    description: 'Rollback table to previous job run with cascade support',
    category: 'operational',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/tables/{database}/{table}/rollback',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "database": {
                              "type": "string",
                              "description": "database parameter"
                      },
                      "table": {
                              "type": "string",
                              "description": "table parameter"
                      },
                      "branch": {
                              "type": "string",
                              "description": "branch parameter"
                      },
                      "rollbackToJobRun": {
                              "type": "string",
                              "description": "rollbackToJobRun parameter"
                      },
                      "reason": {
                              "type": "string",
                              "description": "reason parameter"
                      },
                      "cascade": {
                              "type": "boolean",
                              "description": "cascade parameter"
                      },
                      "isUnmerge": {
                              "type": "boolean",
                              "description": "isUnmerge parameter"
                      },
                      "rollbackToVersion": {
                              "type": "string",
                              "description": "rollbackToVersion parameter"
                      },
                      "rollbackToSnapshot": {
                              "type": "number",
                              "description": "rollbackToSnapshot parameter"
                      }
              },
              "required": [
                      "database",
                      "table",
                      "branch",
                      "rollbackToJobRun",
                      "reason",
                      "cascade"
              ]
      },
    },
    modes: ['cloud'],
  },
  {
    name: 'execute_query',
    description: 'Execute a SQL or PySpark query and return execution ID',
    category: 'query',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/query',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "query": {
                              "type": "string",
                              "description": "query parameter"
                      },
                      "language": {
                              "type": "string",
                              "enum": [
                                      "sql",
                                      "python"
                              ],
                              "description": "language parameter"
                      },
                      "branch": {
                              "type": "string",
                              "description": "branch parameter"
                      },
                      "computeEngine": {
                              "type": "string",
                              "enum": [
                                      "emr-serverless",
                                      "athena"
                              ],
                              "description": "computeEngine parameter"
                      },
                      "parameters": {
                              "type": "array",
                              "items": {
                                      "$schema": "https://json-schema.org/draft/2020-12/schema",
                                      "$id": "QueryParameter.yaml",
                                      "type": "object",
                                      "properties": {
                                              "name": {
                                                      "type": "string",
                                                      "description": "Parameter name (without `@` prefix)"
                                              },
                                              "value": {
                                                      "type": "string",
                                                      "description": "Parameter value (as string, will be cast to appropriate type)"
                                              },
                                              "paramType": {
                                                      "$ref": "ParameterType.yaml",
                                                      "description": "Parameter data type"
                                              },
                                              "isUsed": {
                                                      "type": "boolean",
                                                      "default": false,
                                                      "description": "Whether parameter was detected/used in query"
                                              }
                                      },
                                      "required": [
                                              "name",
                                              "value",
                                              "paramType"
                                      ],
                                      "description": "Query parameter with runtime value\nUsed during query execution to provide parameter values"
                              },
                              "description": "parameters parameter"
                      },
                      "resultSetLimit": {
                              "type": "number",
                              "description": "resultSetLimit parameter"
                      }
              },
              "required": [
                      "query"
              ]
      },
    },
    asyncResultField: 'queryExecutionId',
    asyncResultType: 'query',
  },
  {
    name: 'get_query_results',
    description: 'Get query execution results including data and status',
    category: 'query',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/query/{queryExecutionId}/results',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "queryExecutionId": {
                              "type": "string",
                              "description": "queryExecutionId parameter"
                      },
                      "limit": {
                              "type": "number",
                              "description": "limit parameter"
                      }
              },
              "required": [
                      "queryExecutionId"
              ]
      },
    },
    responseArrayField: 'rows',
  },
  {
    name: 'save_query_as_table',
    description: 'Save query results as a new managed table',
    category: 'query',
    requiresConfirmation: true,
    tier: 'mvp',
    httpMethod: 'POST',
    route: '/query/save-as-table',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "queryExecutionId": {
                              "type": "string",
                              "description": "queryExecutionId parameter"
                      },
                      "tableName": {
                              "type": "string",
                              "description": "tableName parameter"
                      },
                      "description": {
                              "type": "string",
                              "description": "description parameter"
                      },
                      "code": {
                              "$schema": "https://json-schema.org/draft/2020-12/schema",
                              "$id": "TableCode.yaml",
                              "type": "object",
                              "properties": {
                                      "content": {
                                              "type": "string",
                                              "description": "SQL query or Python script content"
                                      },
                                      "language": {
                                              "$ref": "CodeLanguage.yaml",
                                              "description": "Programming language - determines code execution mode"
                                      },
                                      "dialect": {
                                              "$ref": "CodeDialect.yaml",
                                              "description": "Execution dialect - determines runtime environment"
                                      },
                                      "parameters": {
                                              "type": "array",
                                              "items": {
                                                      "$ref": "Parameter.yaml"
                                              },
                                              "description": "User-defined parameters"
                                      },
                                      "systemParameters": {
                                              "type": "array",
                                              "items": {
                                                      "$ref": "SystemParameter.yaml"
                                              },
                                              "description": "System parameters (auto-injected)"
                                      },
                                      "codeHash": {
                                              "type": "string",
                                              "description": "Code version/hash for change detection"
                                      },
                                      "lastModified": {
                                              "type": "string",
                                              "format": "date-time",
                                              "description": "When code was last modified"
                                      }
                              },
                              "required": [
                                      "content",
                                      "language",
                                      "dialect"
                              ],
                              "description": "code parameter"
                      },
                      "schema": {
                              "type": "array",
                              "items": {
                                      "type": "string"
                              },
                              "description": "schema parameter"
                      },
                      "partitionColumns": {
                              "type": "array",
                              "items": {
                                      "type": "string"
                              },
                              "description": "partitionColumns parameter"
                      },
                      "primaryKey": {
                              "type": "array",
                              "items": {
                                      "type": "string"
                              },
                              "description": "primaryKey parameter"
                      },
                      "updateStrategy": {
                              "type": "string",
                              "description": "updateStrategy parameter"
                      },
                      "dependencies": {
                              "$schema": "https://json-schema.org/draft/2020-12/schema",
                              "$id": "SaveAsTableDependencies.yaml",
                              "type": "object",
                              "properties": {
                                      "tables": {
                                              "type": "array",
                                              "items": {
                                                      "$ref": "SaveAsTableDependency.yaml"
                                              },
                                              "description": "Table dependencies"
                                      },
                                      "externalEvents": {
                                              "type": "array",
                                              "items": {
                                                      "$ref": "SaveAsTableEventDependency.yaml"
                                              },
                                              "description": "External event dependencies"
                                      }
                              },
                              "description": "dependencies parameter"
                      },
                      "jobs": {
                              "type": "array",
                              "items": {
                                      "$schema": "https://json-schema.org/draft/2020-12/schema",
                                      "$id": "SaveAsTableJob.yaml",
                                      "type": "object",
                                      "properties": {
                                              "name": {
                                                      "type": "string"
                                              },
                                              "enabled": {
                                                      "type": "boolean",
                                                      "default": true
                                              },
                                              "schedule": {
                                                      "$ref": "SaveAsTableSchedule.yaml"
                                              },
                                              "targetPartition": {
                                                      "$ref": "SaveAsTableTargetPartition.yaml"
                                              },
                                              "dependencyMappings": {
                                                      "$ref": "SaveAsTableDependencyMappings.yaml"
                                              },
                                              "parameterValues": {
                                                      "type": "array",
                                                      "items": {
                                                              "$ref": "SaveAsTableParameter.yaml"
                                                      }
                                              }
                                      },
                                      "required": [
                                              "name",
                                              "schedule"
                                      ]
                              },
                              "description": "jobs parameter"
                      },
                      "initialLoad": {
                              "type": "boolean",
                              "description": "initialLoad parameter"
                      }
              },
              "required": [
                      "queryExecutionId",
                      "tableName",
                      "code",
                      "jobs"
              ]
      },
    },
    asyncResultField: 'executionArn',
    asyncResultType: 'workflow',
  },
  {
    name: 'show_chart',
    description: 'Display a chart visualization inline in the chat. Use this after executing a query to visualize the results. The data should already be aggregated in the SQL query - do not pass raw unaggregated data.',
    category: 'query',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: '',
    route: '',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "vizType": {
                              "type": "string",
                              "enum": [
                                      "bar",
                                      "line",
                                      "pie",
                                      "scatter",
                                      "area",
                                      "table",
                                      "histogram",
                                      "boxplot"
                              ],
                              "description": "Chart type: bar (categories), line (trends), pie (proportions), scatter (correlations), area (trends with volume), histogram (distributions), boxplot (statistical summary), table (details)"
                      },
                      "title": {
                              "type": "string",
                              "description": "Display title for the chart"
                      },
                      "description": {
                              "type": "string",
                              "description": "Brief description of what this chart shows"
                      },
                      "data": {
                              "type": "array",
                              "items": {
                                      "type": "object"
                              },
                              "description": "Chart data as array of records. Each record is an object with column names as keys."
                      },
                      "xAxis": {
                              "type": "string",
                              "description": "Column name for X-axis (category axis). For pie charts, this is the name/label column."
                      },
                      "yAxis": {
                              "type": "string",
                              "description": "Column name for Y-axis (value axis). For pie charts, this is the value column."
                      },
                      "yAxisColumns": {
                              "type": "array",
                              "items": {
                                      "type": "string"
                              },
                              "description": "Additional Y-axis columns for multi-series line/bar charts"
                      },
                      "groupBy": {
                              "type": "string",
                              "description": "Column to group data by for grouped/stacked bar charts"
                      },
                      "options": {
                              "type": "object",
                              "properties": {
                                      "layout": {
                                              "type": "string",
                                              "enum": [
                                                      "horizontal",
                                                      "vertical"
                                              ]
                                      },
                                      "stacked": {
                                              "type": "boolean"
                                      },
                                      "curved": {
                                              "type": "boolean"
                                      },
                                      "donut": {
                                              "type": "boolean"
                                      }
                              },
                              "description": "Chart-specific options"
                      },
                      "valueColumn": {
                              "type": "string",
                              "description": "For histogram/boxplot: The numeric column to analyze (single column)"
                      },
                      "valueColumns": {
                              "type": "array",
                              "items": {
                                      "type": "string"
                              },
                              "description": "For boxplot: Multiple numeric columns to compare distributions side-by-side"
                      },
                      "categoryColumn": {
                              "type": "string",
                              "description": "For boxplot: Optional category column for grouped box plots"
                      },
                      "bins": {
                              "type": "number",
                              "description": "For histogram: Number of bins (optional, auto-calculated if not provided)"
                      },
                      "binWidth": {
                              "type": "number",
                              "description": "For histogram: Width of each bin in data units (alternative to bins count)"
                      }
              },
              "required": [
                      "vizType",
                      "title",
                      "data",
                      "xAxis"
              ]
      },
    },
  },
  {
    name: 'get_workflow_status',
    description: 'Get workflow execution status and step-by-step progress. The input field is executionId; pass the full executionArn string as that value when available. Import execution names are also accepted.',
    category: 'workflow',
    requiresConfirmation: false,
    tier: 'mvp',
    httpMethod: 'GET',
    route: '/workflows/executions/{executionId}',
    inputSchema: {
      json: {
              "type": "object",
              "properties": {
                      "executionId": {
                              "type": "string",
                              "description": "Execution reference. Pass the full executionArn string here when available; import execution names are also accepted."
                      }
              },
              "required": [
                      "executionId"
              ]
      },
    },
    modes: ['cloud'],
  }
];

/**
 * Tool-specific array field mapping for smart response trimming
 */
export const TOOL_ARRAY_FIELDS: Record<string, string> = Object.fromEntries(
  AI_TOOLS
    .filter(tool => tool.responseArrayField)
    .map(tool => [tool.name, tool.responseArrayField!])
);

export function getToolsByTier(tier: AIToolTier): AIToolMetadata[] {
  return AI_TOOLS.filter(tool => tool.tier === tier);
}

export function getToolsByMode(mode: AIToolMode, tier: AIToolTier = 'mvp'): AIToolMetadata[] {
  return AI_TOOLS.filter(tool => tool.tier === tier && (!tool.modes || tool.modes.includes(mode)));
}

export function getToolsByCategory(category: AIToolCategory): AIToolMetadata[] {
  return AI_TOOLS.filter(tool => tool.category === category);
}

export function getBedrockToolSchemas(tier: AIToolTier = 'mvp'): BedrockToolSchema[] {
  return getToolsByTier(tier).map(({ name, description, inputSchema }) => ({
    name,
    description,
    inputSchema,
  }));
}

export function findToolByName(name: string): AIToolMetadata | undefined {
  return AI_TOOLS.find(tool => tool.name === name);
}
