/**
 * CDK Route Definitions
 *
 * Auto-generated from TypeSpec @httpRoute decorators
 * Do not edit this file directly
 *
 * Source: typespec/apis/*.tsp with @httpRoute decorators
 * Generated: 2026-04-03T06:41:21.655Z
 */

export interface RouteDefinition {
  /** Unique route identifier for CDK */
  id: string;
  /** HTTP method */
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  /** Route path with parameters */
  path: string;
  /** Lambda handler name */
  handler: string;
  /** Source TypeSpec model name */
  modelName: string;
}

/**
 * All route definitions
 */
export const ROUTES: RouteDefinition[] = [
  {
    "id": "ListSessions",
    "method": "GET",
    "path": "/ai-chat/sessions",
    "handler": "aiChatApi",
    "modelName": "ListSessionsRequest"
  },
  {
    "id": "GetSession",
    "method": "GET",
    "path": "/ai-chat/sessions/{sessionId}",
    "handler": "aiChatApi",
    "modelName": "GetSessionRequest"
  },
  {
    "id": "DeleteSession",
    "method": "DELETE",
    "path": "/ai-chat/sessions/{sessionId}",
    "handler": "aiChatApi",
    "modelName": "DeleteSessionRequest"
  },
  {
    "id": "GetCompactedRanges",
    "method": "GET",
    "path": "/ai-chat/sessions/{sessionId}/compacted",
    "handler": "aiChatApi",
    "modelName": "GetCompactedRangesRequest"
  },
  {
    "id": "SaveCompactedRange",
    "method": "POST",
    "path": "/ai-chat/sessions/{sessionId}/compacted",
    "handler": "aiChatApi",
    "modelName": "SaveCompactedRangeRequest"
  },
  {
    "id": "StarSession",
    "method": "PUT",
    "path": "/ai-chat/sessions/{sessionId}/star",
    "handler": "aiChatApi",
    "modelName": "StarSessionRequest"
  },
  {
    "id": "ListAiSessions",
    "method": "GET",
    "path": "/ai/sessions",
    "handler": "aiChatApi",
    "modelName": "ListAiSessionsRequest"
  },
  {
    "id": "GetAiSession",
    "method": "GET",
    "path": "/ai/sessions/{sessionId}",
    "handler": "aiChatApi",
    "modelName": "GetAiSessionRequest"
  },
  {
    "id": "DeleteAiSession",
    "method": "DELETE",
    "path": "/ai/sessions/{sessionId}",
    "handler": "aiChatApi",
    "modelName": "DeleteAiSessionRequest"
  },
  {
    "id": "UpdateAiSession",
    "method": "PUT",
    "path": "/ai/sessions/{sessionId}",
    "handler": "aiChatApi",
    "modelName": "UpdateAiSessionRequest"
  },
  {
    "id": "GetAiCompactedRanges",
    "method": "GET",
    "path": "/ai/sessions/{sessionId}/compacted",
    "handler": "aiChatApi",
    "modelName": "GetAiCompactedRangesRequest"
  },
  {
    "id": "SaveAiCompactedRange",
    "method": "POST",
    "path": "/ai/sessions/{sessionId}/compacted",
    "handler": "aiChatApi",
    "modelName": "SaveAiCompactedRangeRequest"
  },
  {
    "id": "StarAiSession",
    "method": "PUT",
    "path": "/ai/sessions/{sessionId}/star",
    "handler": "aiChatApi",
    "modelName": "StarAiSessionRequest"
  },
  {
    "id": "GenerateAiSessionTitle",
    "method": "POST",
    "path": "/ai/sessions/{sessionId}/title",
    "handler": "aiChatApi",
    "modelName": "GenerateAiSessionTitleRequest"
  },
  {
    "id": "ListCommands",
    "method": "GET",
    "path": "/ai/commands",
    "handler": "aiCommandsApi",
    "modelName": "ListCommandsRequest"
  },
  {
    "id": "CreateCommand",
    "method": "POST",
    "path": "/ai/commands",
    "handler": "aiCommandsApi",
    "modelName": "CreateCommandRequest"
  },
  {
    "id": "GetCommand",
    "method": "GET",
    "path": "/ai/commands/{name}",
    "handler": "aiCommandsApi",
    "modelName": "GetCommandRequest"
  },
  {
    "id": "UpdateCommand",
    "method": "PUT",
    "path": "/ai/commands/{name}",
    "handler": "aiCommandsApi",
    "modelName": "UpdateCommandRequest"
  },
  {
    "id": "DeleteCommand",
    "method": "DELETE",
    "path": "/ai/commands/{name}",
    "handler": "aiCommandsApi",
    "modelName": "DeleteCommandRequest"
  },
  {
    "id": "GetMemory",
    "method": "GET",
    "path": "/ai/memory",
    "handler": "aiMemoryApi",
    "modelName": "GetMemoryRequest"
  },
  {
    "id": "UpdateMemory",
    "method": "PUT",
    "path": "/ai/memory",
    "handler": "aiMemoryApi",
    "modelName": "UpdateMemoryRequest"
  },
  {
    "id": "ListSkills",
    "method": "GET",
    "path": "/ai/skills",
    "handler": "aiSkillsApi",
    "modelName": "ListSkillsRequest"
  },
  {
    "id": "CreateSkill",
    "method": "POST",
    "path": "/ai/skills",
    "handler": "aiSkillsApi",
    "modelName": "CreateSkillRequest"
  },
  {
    "id": "GetSkill",
    "method": "GET",
    "path": "/ai/skills/{name}",
    "handler": "aiSkillsApi",
    "modelName": "GetSkillRequest"
  },
  {
    "id": "UpdateSkill",
    "method": "PUT",
    "path": "/ai/skills/{name}",
    "handler": "aiSkillsApi",
    "modelName": "UpdateSkillRequest"
  },
  {
    "id": "DeleteSkill",
    "method": "DELETE",
    "path": "/ai/skills/{name}",
    "handler": "aiSkillsApi",
    "modelName": "DeleteSkillRequest"
  },
  {
    "id": "StartBackfill",
    "method": "POST",
    "path": "/tables/{database}/{table}/backfill",
    "handler": "backfillApi",
    "modelName": "StartBackfillRequest"
  },
  {
    "id": "ListTableBackfills",
    "method": "GET",
    "path": "/tables/{database}/{table}/backfills",
    "handler": "backfillApi",
    "modelName": "ListTableBackfillsRequest"
  },
  {
    "id": "CreateBranch",
    "method": "POST",
    "path": "/tables/{database}/{table}/branches",
    "handler": "branchApi",
    "modelName": "CreateBranchRequest"
  },
  {
    "id": "ListBranches",
    "method": "GET",
    "path": "/tables/{database}/{table}/branches",
    "handler": "branchApi",
    "modelName": "ListBranchesRequest"
  },
  {
    "id": "GetBranch",
    "method": "GET",
    "path": "/tables/{database}/{table}/branches/{branch}",
    "handler": "branchApi",
    "modelName": "GetBranchRequest"
  },
  {
    "id": "DeleteBranch",
    "method": "DELETE",
    "path": "/tables/{database}/{table}/branches/{branch}",
    "handler": "branchApi",
    "modelName": "DeleteBranchRequest"
  },
  {
    "id": "TogglePreview",
    "method": "POST",
    "path": "/tables/{database}/{table}/branches/{branch}/preview",
    "handler": "branchApi",
    "modelName": "TogglePreviewRequest"
  },
  {
    "id": "UpdateBranchSchema",
    "method": "PUT",
    "path": "/tables/{database}/{table}/branches/{branch}/schema",
    "handler": "branchApi",
    "modelName": "UpdateBranchSchemaRequest"
  },
  {
    "id": "MergeBranch",
    "method": "POST",
    "path": "/tables/{database}/{table}/branches/merge",
    "handler": "branchApi",
    "modelName": "MergeBranchRequest"
  },
  {
    "id": "ChatInvoke",
    "method": "POST",
    "path": "/chat/invoke",
    "handler": "chatInvoke",
    "modelName": "ChatInvokeRequest"
  },
  {
    "id": "GetConfig",
    "method": "GET",
    "path": "/config",
    "handler": "configApi",
    "modelName": "GetConfigRequest"
  },
  {
    "id": "UpdateConfig",
    "method": "PUT",
    "path": "/config",
    "handler": "configApi",
    "modelName": "UpdateConfigRequest"
  },
  {
    "id": "GetComputeConfig",
    "method": "GET",
    "path": "/config/compute",
    "handler": "configApi",
    "modelName": "GetComputeConfigRequest"
  },
  {
    "id": "UpdateComputeConfig",
    "method": "PUT",
    "path": "/config/compute",
    "handler": "configApi",
    "modelName": "UpdateComputeConfigRequest"
  },
  {
    "id": "CreateConnectionAPI",
    "method": "POST",
    "path": "/connections",
    "handler": "connectionApi",
    "modelName": "CreateConnectionAPIRequest"
  },
  {
    "id": "ListConnections",
    "method": "GET",
    "path": "/connections",
    "handler": "connectionApi",
    "modelName": "ListConnectionsRequest"
  },
  {
    "id": "GetConnection",
    "method": "GET",
    "path": "/connections/{connectionId}",
    "handler": "connectionApi",
    "modelName": "GetConnectionRequest"
  },
  {
    "id": "DeleteConnection",
    "method": "DELETE",
    "path": "/connections/{connectionId}",
    "handler": "connectionApi",
    "modelName": "DeleteConnectionRequest"
  },
  {
    "id": "AnalyzeColumnDistribution",
    "method": "POST",
    "path": "/connections/{connectionId}/distribution",
    "handler": "connectionApi",
    "modelName": "AnalyzeColumnDistributionRequest"
  },
  {
    "id": "QueryExternalConnection",
    "method": "POST",
    "path": "/connections/{connectionId}/query",
    "handler": "connectionApi",
    "modelName": "QueryExternalConnectionRequest"
  },
  {
    "id": "DetectConnectionSchema",
    "method": "POST",
    "path": "/connections/{connectionId}/schema",
    "handler": "connectionApi",
    "modelName": "DetectConnectionSchemaRequest"
  },
  {
    "id": "ListConnectionTables",
    "method": "POST",
    "path": "/connections/{connectionId}/tables",
    "handler": "connectionApi",
    "modelName": "ListConnectionTablesRequest"
  },
  {
    "id": "TestSavedConnection",
    "method": "POST",
    "path": "/connections/{connectionId}/test",
    "handler": "connectionApi",
    "modelName": "TestSavedConnectionRequest"
  },
  {
    "id": "TestConnectionAPI",
    "method": "POST",
    "path": "/connections/test",
    "handler": "connectionApi",
    "modelName": "TestConnectionAPIRequest"
  },
  {
    "id": "ListDatabases",
    "method": "GET",
    "path": "/databases",
    "handler": "databaseApi",
    "modelName": "ListDatabasesRequest"
  },
  {
    "id": "CreateDatabase",
    "method": "POST",
    "path": "/databases",
    "handler": "databaseApi",
    "modelName": "CreateDatabaseRequest"
  },
  {
    "id": "GetDatabase",
    "method": "GET",
    "path": "/databases/{database}",
    "handler": "databaseApi",
    "modelName": "GetDatabaseRequest"
  },
  {
    "id": "DeleteDatabase",
    "method": "DELETE",
    "path": "/databases/{database}",
    "handler": "databaseApi",
    "modelName": "DeleteDatabaseRequest"
  },
  {
    "id": "ListActivityEvents",
    "method": "GET",
    "path": "/events",
    "handler": "eventsApi",
    "modelName": "ListActivityEventsRequest"
  },
  {
    "id": "GetActivityEvent",
    "method": "GET",
    "path": "/events/{eventId}",
    "handler": "eventsApi",
    "modelName": "GetActivityEventRequest"
  },
  {
    "id": "DetectS3Schema",
    "method": "POST",
    "path": "/import/detect",
    "handler": "importApi",
    "modelName": "DetectS3SchemaRequest"
  },
  {
    "id": "DetectGlueSchema",
    "method": "POST",
    "path": "/import/detect-glue",
    "handler": "importApi",
    "modelName": "DetectGlueSchemaRequest"
  },
  {
    "id": "ImportFromFileUpload",
    "method": "POST",
    "path": "/import/file-upload",
    "handler": "importApi",
    "modelName": "ImportFromFileUploadRequest"
  },
  {
    "id": "ImportFromGlue",
    "method": "POST",
    "path": "/import/glue",
    "handler": "importApi",
    "modelName": "ImportFromGlueRequest"
  },
  {
    "id": "ImportFromPaste",
    "method": "POST",
    "path": "/import/paste",
    "handler": "importApi",
    "modelName": "ImportFromPasteRequest"
  },
  {
    "id": "ImportFromPostgres",
    "method": "POST",
    "path": "/import/postgres",
    "handler": "importApi",
    "modelName": "ImportFromPostgresRequest"
  },
  {
    "id": "ImportFromS3",
    "method": "POST",
    "path": "/import/s3",
    "handler": "importApi",
    "modelName": "ImportFromS3Request"
  },
  {
    "id": "ImportFromSnowflake",
    "method": "POST",
    "path": "/import/snowflake",
    "handler": "importApi",
    "modelName": "ImportFromSnowflakeRequest"
  },
  {
    "id": "UploadPresign",
    "method": "POST",
    "path": "/import/upload/presign",
    "handler": "importApi",
    "modelName": "UploadPresignRequest"
  },
  {
    "id": "SubmitJob",
    "method": "POST",
    "path": "/jobs",
    "handler": "jobApi",
    "modelName": "SubmitJobRequest"
  },
  {
    "id": "ListJobRuns",
    "method": "GET",
    "path": "/jobs",
    "handler": "jobApi",
    "modelName": "ListJobRunsRequest"
  },
  {
    "id": "GetJobRun",
    "method": "GET",
    "path": "/jobs/{jobRunId}",
    "handler": "jobApi",
    "modelName": "GetJobRunRequest"
  },
  {
    "id": "CancelJobRun",
    "method": "DELETE",
    "path": "/jobs/{jobRunId}",
    "handler": "jobApi",
    "modelName": "CancelJobRunRequest"
  },
  {
    "id": "CancelJob",
    "method": "POST",
    "path": "/jobs/{jobRunId}/cancel",
    "handler": "jobApi",
    "modelName": "CancelJobRequest"
  },
  {
    "id": "GetDependencyStatus",
    "method": "GET",
    "path": "/jobs/{jobRunId}/dependencies",
    "handler": "jobApi",
    "modelName": "GetDependencyStatusRequest"
  },
  {
    "id": "GetJobRunDetails",
    "method": "GET",
    "path": "/jobs/{jobRunId}/details",
    "handler": "jobApi",
    "modelName": "GetJobRunDetailsRequest"
  },
  {
    "id": "GetJobRunLogContent",
    "method": "GET",
    "path": "/jobs/{jobRunId}/logs",
    "handler": "jobApi",
    "modelName": "GetJobRunLogContentRequest"
  },
  {
    "id": "RerunJobRun",
    "method": "POST",
    "path": "/jobs/{jobRunId}/rerun",
    "handler": "jobApi",
    "modelName": "RerunJobRunRequest"
  },
  {
    "id": "TriggerJobRun",
    "method": "POST",
    "path": "/tables/{database}/{table}/jobs/{jobId}/run",
    "handler": "jobApi",
    "modelName": "TriggerJobRunRequest"
  },
  {
    "id": "CascadeExecute",
    "method": "POST",
    "path": "/databases/{database}/tables/{table}/lineage/cascade-execute",
    "handler": "lineageApi",
    "modelName": "CascadeExecuteRequest"
  },
  {
    "id": "CascadePreview",
    "method": "POST",
    "path": "/databases/{database}/tables/{table}/lineage/cascade-preview",
    "handler": "lineageApi",
    "modelName": "CascadePreviewRequest"
  },
  {
    "id": "GetLineageImpact",
    "method": "GET",
    "path": "/databases/{database}/tables/{table}/lineage/impact",
    "handler": "lineageApi",
    "modelName": "GetLineageImpactRequest"
  },
  {
    "id": "GetLineageTrace",
    "method": "GET",
    "path": "/databases/{database}/tables/{table}/lineage/trace",
    "handler": "lineageApi",
    "modelName": "GetLineageTraceRequest"
  },
  {
    "id": "ExecuteQuery",
    "method": "POST",
    "path": "/query",
    "handler": "queryApi",
    "modelName": "ExecuteQueryRequest"
  },
  {
    "id": "GetQueryResults",
    "method": "GET",
    "path": "/query/{queryExecutionId}/results",
    "handler": "queryApi",
    "modelName": "GetQueryResultsRequest"
  },
  {
    "id": "GetQueryStatus",
    "method": "GET",
    "path": "/query/{queryExecutionId}/status",
    "handler": "queryApi",
    "modelName": "GetQueryStatusRequest"
  },
  {
    "id": "StopQuery",
    "method": "POST",
    "path": "/query/{queryExecutionId}/stop",
    "handler": "queryApi",
    "modelName": "StopQueryRequest"
  },
  {
    "id": "QueryDetectSchema",
    "method": "POST",
    "path": "/query/detect-schema",
    "handler": "queryApi",
    "modelName": "QueryDetectSchemaRequest"
  },
  {
    "id": "GenerateQuery",
    "method": "POST",
    "path": "/query/generate",
    "handler": "queryApi",
    "modelName": "GenerateQueryRequest"
  },
  {
    "id": "SaveQueryAsTable",
    "method": "POST",
    "path": "/query/save-as-table",
    "handler": "queryApi",
    "modelName": "SaveQueryAsTableRequest"
  },
  {
    "id": "GenerateVisuals",
    "method": "POST",
    "path": "/query/visuals",
    "handler": "queryApi",
    "modelName": "GenerateVisualsRequest"
  },
  {
    "id": "ExecuteVisualFullData",
    "method": "POST",
    "path": "/query/visuals/full-data",
    "handler": "queryApi",
    "modelName": "ExecuteVisualFullDataRequest"
  },
  {
    "id": "ListRoles",
    "method": "GET",
    "path": "/roles",
    "handler": "rbacApi",
    "modelName": "ListRolesRequest"
  },
  {
    "id": "CreateRole",
    "method": "POST",
    "path": "/roles",
    "handler": "rbacApi",
    "modelName": "CreateRoleRequest"
  },
  {
    "id": "GetRole",
    "method": "GET",
    "path": "/roles/{roleId}",
    "handler": "rbacApi",
    "modelName": "GetRoleRequest"
  },
  {
    "id": "UpdateRole",
    "method": "PUT",
    "path": "/roles/{roleId}",
    "handler": "rbacApi",
    "modelName": "UpdateRoleRequest"
  },
  {
    "id": "DeleteRole",
    "method": "DELETE",
    "path": "/roles/{roleId}",
    "handler": "rbacApi",
    "modelName": "DeleteRoleRequest"
  },
  {
    "id": "ListTeams",
    "method": "GET",
    "path": "/teams",
    "handler": "rbacApi",
    "modelName": "ListTeamsRequest"
  },
  {
    "id": "CreateTeam",
    "method": "POST",
    "path": "/teams",
    "handler": "rbacApi",
    "modelName": "CreateTeamRequest"
  },
  {
    "id": "GetTeam",
    "method": "GET",
    "path": "/teams/{teamId}",
    "handler": "rbacApi",
    "modelName": "GetTeamRequest"
  },
  {
    "id": "UpdateTeam",
    "method": "PUT",
    "path": "/teams/{teamId}",
    "handler": "rbacApi",
    "modelName": "UpdateTeamRequest"
  },
  {
    "id": "DeleteTeam",
    "method": "DELETE",
    "path": "/teams/{teamId}",
    "handler": "rbacApi",
    "modelName": "DeleteTeamRequest"
  },
  {
    "id": "ListUsers",
    "method": "GET",
    "path": "/users",
    "handler": "rbacApi",
    "modelName": "ListUsersRequest"
  },
  {
    "id": "CreateUser",
    "method": "POST",
    "path": "/users",
    "handler": "rbacApi",
    "modelName": "CreateUserRequest"
  },
  {
    "id": "GetUser",
    "method": "GET",
    "path": "/users/{username}",
    "handler": "rbacApi",
    "modelName": "GetUserRequest"
  },
  {
    "id": "UpdateUser",
    "method": "PUT",
    "path": "/users/{username}",
    "handler": "rbacApi",
    "modelName": "UpdateUserRequest"
  },
  {
    "id": "DeleteUser",
    "method": "DELETE",
    "path": "/users/{username}",
    "handler": "rbacApi",
    "modelName": "DeleteUserRequest"
  },
  {
    "id": "GetRollbackCascadeTree",
    "method": "GET",
    "path": "/rollback/{rollbackId}",
    "handler": "rollbackTree",
    "modelName": "GetRollbackCascadeTreeRequest"
  },
  {
    "id": "GetTableRollbackTree",
    "method": "GET",
    "path": "/tables/{database}/{table}/rollback-tree",
    "handler": "rollbackTree",
    "modelName": "GetTableRollbackTreeRequest"
  },
  {
    "id": "SearchCatalog",
    "method": "GET",
    "path": "/search",
    "handler": "tableApi",
    "modelName": "SearchCatalogRequest"
  },
  {
    "id": "CreateTable",
    "method": "POST",
    "path": "/tables",
    "handler": "tableApi",
    "modelName": "CreateTableRequest"
  },
  {
    "id": "ListTables",
    "method": "GET",
    "path": "/tables",
    "handler": "tableApi",
    "modelName": "ListTablesRequest"
  },
  {
    "id": "GetTable",
    "method": "GET",
    "path": "/tables/{database}/{table}",
    "handler": "tableApi",
    "modelName": "GetTableRequest"
  },
  {
    "id": "UpdateTable",
    "method": "PUT",
    "path": "/tables/{database}/{table}",
    "handler": "tableApi",
    "modelName": "UpdateTableRequest"
  },
  {
    "id": "DeleteTable",
    "method": "DELETE",
    "path": "/tables/{database}/{table}",
    "handler": "tableApi",
    "modelName": "DeleteTableRequest"
  },
  {
    "id": "GetCrawler",
    "method": "GET",
    "path": "/tables/{database}/{table}/crawler",
    "handler": "tableApi",
    "modelName": "GetCrawlerRequest"
  },
  {
    "id": "StartCrawler",
    "method": "POST",
    "path": "/tables/{database}/{table}/crawler/run",
    "handler": "tableApi",
    "modelName": "StartCrawlerRequest"
  },
  {
    "id": "UpdateCrawler",
    "method": "PUT",
    "path": "/tables/{database}/{table}/crawler/schedule",
    "handler": "tableApi",
    "modelName": "UpdateCrawlerRequest"
  },
  {
    "id": "GetTableDependencies",
    "method": "GET",
    "path": "/tables/{database}/{table}/dependencies",
    "handler": "tableApi",
    "modelName": "GetTableDependenciesRequest"
  },
  {
    "id": "GetTableDependents",
    "method": "GET",
    "path": "/tables/{database}/{table}/dependents",
    "handler": "tableApi",
    "modelName": "GetTableDependentsRequest"
  },
  {
    "id": "CreateJob",
    "method": "POST",
    "path": "/tables/{database}/{table}/jobs",
    "handler": "tableApi",
    "modelName": "CreateJobRequest"
  },
  {
    "id": "UpdateJob",
    "method": "PUT",
    "path": "/tables/{database}/{table}/jobs/{jobId}",
    "handler": "tableApi",
    "modelName": "UpdateJobRequest"
  },
  {
    "id": "Rollback",
    "method": "POST",
    "path": "/tables/{database}/{table}/rollback",
    "handler": "tableApi",
    "modelName": "RollbackRequest"
  },
  {
    "id": "GetTableSchema",
    "method": "GET",
    "path": "/tables/{database}/{table}/schema",
    "handler": "tableApi",
    "modelName": "GetTableSchemaRequest"
  },
  {
    "id": "ListSnapshots",
    "method": "GET",
    "path": "/tables/{database}/{table}/snapshots",
    "handler": "tableApi",
    "modelName": "ListSnapshotsRequest"
  },
  {
    "id": "ListWorkflowTypes",
    "method": "GET",
    "path": "/workflows",
    "handler": "workflowApi",
    "modelName": "ListWorkflowTypesRequest"
  },
  {
    "id": "GetWorkflowType",
    "method": "GET",
    "path": "/workflows/{id}",
    "handler": "workflowApi",
    "modelName": "GetWorkflowTypeRequest"
  },
  {
    "id": "ListWorkflowExecutions",
    "method": "GET",
    "path": "/workflows/{id}/executions",
    "handler": "workflowApi",
    "modelName": "ListWorkflowExecutionsRequest"
  },
  {
    "id": "GetWorkflowExecution",
    "method": "GET",
    "path": "/workflows/executions/{executionId}",
    "handler": "workflowApi",
    "modelName": "GetWorkflowExecutionRequest"
  },
  {
    "id": "CancelWorkflowExecution",
    "method": "POST",
    "path": "/workflows/executions/{executionId}/cancel",
    "handler": "workflowApi",
    "modelName": "CancelWorkflowExecutionRequest"
  },
  {
    "id": "RetryWorkflowExecution",
    "method": "POST",
    "path": "/workflows/executions/{executionId}/retry",
    "handler": "workflowApi",
    "modelName": "RetryWorkflowExecutionRequest"
  }
];

/**
 * Routes grouped by handler
 */
export const ROUTES_BY_HANDLER: Record<string, RouteDefinition[]> = {
  "configApi": [
    {
      "id": "GetConfig",
      "method": "GET",
      "path": "/config",
      "handler": "configApi",
      "modelName": "GetConfigRequest"
    },
    {
      "id": "UpdateConfig",
      "method": "PUT",
      "path": "/config",
      "handler": "configApi",
      "modelName": "UpdateConfigRequest"
    },
    {
      "id": "GetComputeConfig",
      "method": "GET",
      "path": "/config/compute",
      "handler": "configApi",
      "modelName": "GetComputeConfigRequest"
    },
    {
      "id": "UpdateComputeConfig",
      "method": "PUT",
      "path": "/config/compute",
      "handler": "configApi",
      "modelName": "UpdateComputeConfigRequest"
    }
  ],
  "tableApi": [
    {
      "id": "GetTable",
      "method": "GET",
      "path": "/tables/{database}/{table}",
      "handler": "tableApi",
      "modelName": "GetTableRequest"
    },
    {
      "id": "CreateTable",
      "method": "POST",
      "path": "/tables",
      "handler": "tableApi",
      "modelName": "CreateTableRequest"
    },
    {
      "id": "UpdateTable",
      "method": "PUT",
      "path": "/tables/{database}/{table}",
      "handler": "tableApi",
      "modelName": "UpdateTableRequest"
    },
    {
      "id": "DeleteTable",
      "method": "DELETE",
      "path": "/tables/{database}/{table}",
      "handler": "tableApi",
      "modelName": "DeleteTableRequest"
    },
    {
      "id": "ListTables",
      "method": "GET",
      "path": "/tables",
      "handler": "tableApi",
      "modelName": "ListTablesRequest"
    },
    {
      "id": "GetTableDependents",
      "method": "GET",
      "path": "/tables/{database}/{table}/dependents",
      "handler": "tableApi",
      "modelName": "GetTableDependentsRequest"
    },
    {
      "id": "GetTableDependencies",
      "method": "GET",
      "path": "/tables/{database}/{table}/dependencies",
      "handler": "tableApi",
      "modelName": "GetTableDependenciesRequest"
    },
    {
      "id": "GetTableSchema",
      "method": "GET",
      "path": "/tables/{database}/{table}/schema",
      "handler": "tableApi",
      "modelName": "GetTableSchemaRequest"
    },
    {
      "id": "ListSnapshots",
      "method": "GET",
      "path": "/tables/{database}/{table}/snapshots",
      "handler": "tableApi",
      "modelName": "ListSnapshotsRequest"
    },
    {
      "id": "SearchCatalog",
      "method": "GET",
      "path": "/search",
      "handler": "tableApi",
      "modelName": "SearchCatalogRequest"
    },
    {
      "id": "Rollback",
      "method": "POST",
      "path": "/tables/{database}/{table}/rollback",
      "handler": "tableApi",
      "modelName": "RollbackRequest"
    },
    {
      "id": "CreateJob",
      "method": "POST",
      "path": "/tables/{database}/{table}/jobs",
      "handler": "tableApi",
      "modelName": "CreateJobRequest"
    },
    {
      "id": "UpdateJob",
      "method": "PUT",
      "path": "/tables/{database}/{table}/jobs/{jobId}",
      "handler": "tableApi",
      "modelName": "UpdateJobRequest"
    },
    {
      "id": "GetCrawler",
      "method": "GET",
      "path": "/tables/{database}/{table}/crawler",
      "handler": "tableApi",
      "modelName": "GetCrawlerRequest"
    },
    {
      "id": "StartCrawler",
      "method": "POST",
      "path": "/tables/{database}/{table}/crawler/run",
      "handler": "tableApi",
      "modelName": "StartCrawlerRequest"
    },
    {
      "id": "UpdateCrawler",
      "method": "PUT",
      "path": "/tables/{database}/{table}/crawler/schedule",
      "handler": "tableApi",
      "modelName": "UpdateCrawlerRequest"
    }
  ],
  "rollbackTree": [
    {
      "id": "GetTableRollbackTree",
      "method": "GET",
      "path": "/tables/{database}/{table}/rollback-tree",
      "handler": "rollbackTree",
      "modelName": "GetTableRollbackTreeRequest"
    },
    {
      "id": "GetRollbackCascadeTree",
      "method": "GET",
      "path": "/rollback/{rollbackId}",
      "handler": "rollbackTree",
      "modelName": "GetRollbackCascadeTreeRequest"
    }
  ],
  "databaseApi": [
    {
      "id": "ListDatabases",
      "method": "GET",
      "path": "/databases",
      "handler": "databaseApi",
      "modelName": "ListDatabasesRequest"
    },
    {
      "id": "GetDatabase",
      "method": "GET",
      "path": "/databases/{database}",
      "handler": "databaseApi",
      "modelName": "GetDatabaseRequest"
    },
    {
      "id": "CreateDatabase",
      "method": "POST",
      "path": "/databases",
      "handler": "databaseApi",
      "modelName": "CreateDatabaseRequest"
    },
    {
      "id": "DeleteDatabase",
      "method": "DELETE",
      "path": "/databases/{database}",
      "handler": "databaseApi",
      "modelName": "DeleteDatabaseRequest"
    }
  ],
  "branchApi": [
    {
      "id": "CreateBranch",
      "method": "POST",
      "path": "/tables/{database}/{table}/branches",
      "handler": "branchApi",
      "modelName": "CreateBranchRequest"
    },
    {
      "id": "ListBranches",
      "method": "GET",
      "path": "/tables/{database}/{table}/branches",
      "handler": "branchApi",
      "modelName": "ListBranchesRequest"
    },
    {
      "id": "GetBranch",
      "method": "GET",
      "path": "/tables/{database}/{table}/branches/{branch}",
      "handler": "branchApi",
      "modelName": "GetBranchRequest"
    },
    {
      "id": "DeleteBranch",
      "method": "DELETE",
      "path": "/tables/{database}/{table}/branches/{branch}",
      "handler": "branchApi",
      "modelName": "DeleteBranchRequest"
    },
    {
      "id": "MergeBranch",
      "method": "POST",
      "path": "/tables/{database}/{table}/branches/merge",
      "handler": "branchApi",
      "modelName": "MergeBranchRequest"
    },
    {
      "id": "TogglePreview",
      "method": "POST",
      "path": "/tables/{database}/{table}/branches/{branch}/preview",
      "handler": "branchApi",
      "modelName": "TogglePreviewRequest"
    },
    {
      "id": "UpdateBranchSchema",
      "method": "PUT",
      "path": "/tables/{database}/{table}/branches/{branch}/schema",
      "handler": "branchApi",
      "modelName": "UpdateBranchSchemaRequest"
    }
  ],
  "jobApi": [
    {
      "id": "TriggerJobRun",
      "method": "POST",
      "path": "/tables/{database}/{table}/jobs/{jobId}/run",
      "handler": "jobApi",
      "modelName": "TriggerJobRunRequest"
    },
    {
      "id": "SubmitJob",
      "method": "POST",
      "path": "/jobs",
      "handler": "jobApi",
      "modelName": "SubmitJobRequest"
    },
    {
      "id": "GetJobRun",
      "method": "GET",
      "path": "/jobs/{jobRunId}",
      "handler": "jobApi",
      "modelName": "GetJobRunRequest"
    },
    {
      "id": "ListJobRuns",
      "method": "GET",
      "path": "/jobs",
      "handler": "jobApi",
      "modelName": "ListJobRunsRequest"
    },
    {
      "id": "CancelJob",
      "method": "POST",
      "path": "/jobs/{jobRunId}/cancel",
      "handler": "jobApi",
      "modelName": "CancelJobRequest"
    },
    {
      "id": "GetDependencyStatus",
      "method": "GET",
      "path": "/jobs/{jobRunId}/dependencies",
      "handler": "jobApi",
      "modelName": "GetDependencyStatusRequest"
    },
    {
      "id": "GetJobRunDetails",
      "method": "GET",
      "path": "/jobs/{jobRunId}/details",
      "handler": "jobApi",
      "modelName": "GetJobRunDetailsRequest"
    },
    {
      "id": "GetJobRunLogContent",
      "method": "GET",
      "path": "/jobs/{jobRunId}/logs",
      "handler": "jobApi",
      "modelName": "GetJobRunLogContentRequest"
    },
    {
      "id": "CancelJobRun",
      "method": "DELETE",
      "path": "/jobs/{jobRunId}",
      "handler": "jobApi",
      "modelName": "CancelJobRunRequest"
    },
    {
      "id": "RerunJobRun",
      "method": "POST",
      "path": "/jobs/{jobRunId}/rerun",
      "handler": "jobApi",
      "modelName": "RerunJobRunRequest"
    }
  ],
  "queryApi": [
    {
      "id": "ExecuteQuery",
      "method": "POST",
      "path": "/query",
      "handler": "queryApi",
      "modelName": "ExecuteQueryRequest"
    },
    {
      "id": "GetQueryResults",
      "method": "GET",
      "path": "/query/{queryExecutionId}/results",
      "handler": "queryApi",
      "modelName": "GetQueryResultsRequest"
    },
    {
      "id": "SaveQueryAsTable",
      "method": "POST",
      "path": "/query/save-as-table",
      "handler": "queryApi",
      "modelName": "SaveQueryAsTableRequest"
    },
    {
      "id": "GenerateQuery",
      "method": "POST",
      "path": "/query/generate",
      "handler": "queryApi",
      "modelName": "GenerateQueryRequest"
    },
    {
      "id": "GetQueryStatus",
      "method": "GET",
      "path": "/query/{queryExecutionId}/status",
      "handler": "queryApi",
      "modelName": "GetQueryStatusRequest"
    },
    {
      "id": "StopQuery",
      "method": "POST",
      "path": "/query/{queryExecutionId}/stop",
      "handler": "queryApi",
      "modelName": "StopQueryRequest"
    },
    {
      "id": "QueryDetectSchema",
      "method": "POST",
      "path": "/query/detect-schema",
      "handler": "queryApi",
      "modelName": "QueryDetectSchemaRequest"
    },
    {
      "id": "GenerateVisuals",
      "method": "POST",
      "path": "/query/visuals",
      "handler": "queryApi",
      "modelName": "GenerateVisualsRequest"
    },
    {
      "id": "ExecuteVisualFullData",
      "method": "POST",
      "path": "/query/visuals/full-data",
      "handler": "queryApi",
      "modelName": "ExecuteVisualFullDataRequest"
    }
  ],
  "importApi": [
    {
      "id": "ImportFromS3",
      "method": "POST",
      "path": "/import/s3",
      "handler": "importApi",
      "modelName": "ImportFromS3Request"
    },
    {
      "id": "ImportFromGlue",
      "method": "POST",
      "path": "/import/glue",
      "handler": "importApi",
      "modelName": "ImportFromGlueRequest"
    },
    {
      "id": "ImportFromPaste",
      "method": "POST",
      "path": "/import/paste",
      "handler": "importApi",
      "modelName": "ImportFromPasteRequest"
    },
    {
      "id": "DetectS3Schema",
      "method": "POST",
      "path": "/import/detect",
      "handler": "importApi",
      "modelName": "DetectS3SchemaRequest"
    },
    {
      "id": "DetectGlueSchema",
      "method": "POST",
      "path": "/import/detect-glue",
      "handler": "importApi",
      "modelName": "DetectGlueSchemaRequest"
    },
    {
      "id": "ImportFromPostgres",
      "method": "POST",
      "path": "/import/postgres",
      "handler": "importApi",
      "modelName": "ImportFromPostgresRequest"
    },
    {
      "id": "ImportFromSnowflake",
      "method": "POST",
      "path": "/import/snowflake",
      "handler": "importApi",
      "modelName": "ImportFromSnowflakeRequest"
    },
    {
      "id": "UploadPresign",
      "method": "POST",
      "path": "/import/upload/presign",
      "handler": "importApi",
      "modelName": "UploadPresignRequest"
    },
    {
      "id": "ImportFromFileUpload",
      "method": "POST",
      "path": "/import/file-upload",
      "handler": "importApi",
      "modelName": "ImportFromFileUploadRequest"
    }
  ],
  "connectionApi": [
    {
      "id": "CreateConnectionAPI",
      "method": "POST",
      "path": "/connections",
      "handler": "connectionApi",
      "modelName": "CreateConnectionAPIRequest"
    },
    {
      "id": "ListConnections",
      "method": "GET",
      "path": "/connections",
      "handler": "connectionApi",
      "modelName": "ListConnectionsRequest"
    },
    {
      "id": "GetConnection",
      "method": "GET",
      "path": "/connections/{connectionId}",
      "handler": "connectionApi",
      "modelName": "GetConnectionRequest"
    },
    {
      "id": "DeleteConnection",
      "method": "DELETE",
      "path": "/connections/{connectionId}",
      "handler": "connectionApi",
      "modelName": "DeleteConnectionRequest"
    },
    {
      "id": "TestConnectionAPI",
      "method": "POST",
      "path": "/connections/test",
      "handler": "connectionApi",
      "modelName": "TestConnectionAPIRequest"
    },
    {
      "id": "TestSavedConnection",
      "method": "POST",
      "path": "/connections/{connectionId}/test",
      "handler": "connectionApi",
      "modelName": "TestSavedConnectionRequest"
    },
    {
      "id": "ListConnectionTables",
      "method": "POST",
      "path": "/connections/{connectionId}/tables",
      "handler": "connectionApi",
      "modelName": "ListConnectionTablesRequest"
    },
    {
      "id": "DetectConnectionSchema",
      "method": "POST",
      "path": "/connections/{connectionId}/schema",
      "handler": "connectionApi",
      "modelName": "DetectConnectionSchemaRequest"
    },
    {
      "id": "AnalyzeColumnDistribution",
      "method": "POST",
      "path": "/connections/{connectionId}/distribution",
      "handler": "connectionApi",
      "modelName": "AnalyzeColumnDistributionRequest"
    },
    {
      "id": "QueryExternalConnection",
      "method": "POST",
      "path": "/connections/{connectionId}/query",
      "handler": "connectionApi",
      "modelName": "QueryExternalConnectionRequest"
    }
  ],
  "workflowApi": [
    {
      "id": "ListWorkflowTypes",
      "method": "GET",
      "path": "/workflows",
      "handler": "workflowApi",
      "modelName": "ListWorkflowTypesRequest"
    },
    {
      "id": "GetWorkflowType",
      "method": "GET",
      "path": "/workflows/{id}",
      "handler": "workflowApi",
      "modelName": "GetWorkflowTypeRequest"
    },
    {
      "id": "ListWorkflowExecutions",
      "method": "GET",
      "path": "/workflows/{id}/executions",
      "handler": "workflowApi",
      "modelName": "ListWorkflowExecutionsRequest"
    },
    {
      "id": "GetWorkflowExecution",
      "method": "GET",
      "path": "/workflows/executions/{executionId}",
      "handler": "workflowApi",
      "modelName": "GetWorkflowExecutionRequest"
    },
    {
      "id": "RetryWorkflowExecution",
      "method": "POST",
      "path": "/workflows/executions/{executionId}/retry",
      "handler": "workflowApi",
      "modelName": "RetryWorkflowExecutionRequest"
    },
    {
      "id": "CancelWorkflowExecution",
      "method": "POST",
      "path": "/workflows/executions/{executionId}/cancel",
      "handler": "workflowApi",
      "modelName": "CancelWorkflowExecutionRequest"
    }
  ],
  "rbacApi": [
    {
      "id": "ListUsers",
      "method": "GET",
      "path": "/users",
      "handler": "rbacApi",
      "modelName": "ListUsersRequest"
    },
    {
      "id": "CreateUser",
      "method": "POST",
      "path": "/users",
      "handler": "rbacApi",
      "modelName": "CreateUserRequest"
    },
    {
      "id": "GetUser",
      "method": "GET",
      "path": "/users/{username}",
      "handler": "rbacApi",
      "modelName": "GetUserRequest"
    },
    {
      "id": "UpdateUser",
      "method": "PUT",
      "path": "/users/{username}",
      "handler": "rbacApi",
      "modelName": "UpdateUserRequest"
    },
    {
      "id": "DeleteUser",
      "method": "DELETE",
      "path": "/users/{username}",
      "handler": "rbacApi",
      "modelName": "DeleteUserRequest"
    },
    {
      "id": "ListTeams",
      "method": "GET",
      "path": "/teams",
      "handler": "rbacApi",
      "modelName": "ListTeamsRequest"
    },
    {
      "id": "CreateTeam",
      "method": "POST",
      "path": "/teams",
      "handler": "rbacApi",
      "modelName": "CreateTeamRequest"
    },
    {
      "id": "GetTeam",
      "method": "GET",
      "path": "/teams/{teamId}",
      "handler": "rbacApi",
      "modelName": "GetTeamRequest"
    },
    {
      "id": "UpdateTeam",
      "method": "PUT",
      "path": "/teams/{teamId}",
      "handler": "rbacApi",
      "modelName": "UpdateTeamRequest"
    },
    {
      "id": "DeleteTeam",
      "method": "DELETE",
      "path": "/teams/{teamId}",
      "handler": "rbacApi",
      "modelName": "DeleteTeamRequest"
    },
    {
      "id": "ListRoles",
      "method": "GET",
      "path": "/roles",
      "handler": "rbacApi",
      "modelName": "ListRolesRequest"
    },
    {
      "id": "CreateRole",
      "method": "POST",
      "path": "/roles",
      "handler": "rbacApi",
      "modelName": "CreateRoleRequest"
    },
    {
      "id": "GetRole",
      "method": "GET",
      "path": "/roles/{roleId}",
      "handler": "rbacApi",
      "modelName": "GetRoleRequest"
    },
    {
      "id": "UpdateRole",
      "method": "PUT",
      "path": "/roles/{roleId}",
      "handler": "rbacApi",
      "modelName": "UpdateRoleRequest"
    },
    {
      "id": "DeleteRole",
      "method": "DELETE",
      "path": "/roles/{roleId}",
      "handler": "rbacApi",
      "modelName": "DeleteRoleRequest"
    }
  ],
  "backfillApi": [
    {
      "id": "StartBackfill",
      "method": "POST",
      "path": "/tables/{database}/{table}/backfill",
      "handler": "backfillApi",
      "modelName": "StartBackfillRequest"
    },
    {
      "id": "ListTableBackfills",
      "method": "GET",
      "path": "/tables/{database}/{table}/backfills",
      "handler": "backfillApi",
      "modelName": "ListTableBackfillsRequest"
    }
  ],
  "aiChatApi": [
    {
      "id": "ListSessions",
      "method": "GET",
      "path": "/ai-chat/sessions",
      "handler": "aiChatApi",
      "modelName": "ListSessionsRequest"
    },
    {
      "id": "GetSession",
      "method": "GET",
      "path": "/ai-chat/sessions/{sessionId}",
      "handler": "aiChatApi",
      "modelName": "GetSessionRequest"
    },
    {
      "id": "DeleteSession",
      "method": "DELETE",
      "path": "/ai-chat/sessions/{sessionId}",
      "handler": "aiChatApi",
      "modelName": "DeleteSessionRequest"
    },
    {
      "id": "StarSession",
      "method": "PUT",
      "path": "/ai-chat/sessions/{sessionId}/star",
      "handler": "aiChatApi",
      "modelName": "StarSessionRequest"
    },
    {
      "id": "GetCompactedRanges",
      "method": "GET",
      "path": "/ai-chat/sessions/{sessionId}/compacted",
      "handler": "aiChatApi",
      "modelName": "GetCompactedRangesRequest"
    },
    {
      "id": "ListAiSessions",
      "method": "GET",
      "path": "/ai/sessions",
      "handler": "aiChatApi",
      "modelName": "ListAiSessionsRequest"
    },
    {
      "id": "GetAiSession",
      "method": "GET",
      "path": "/ai/sessions/{sessionId}",
      "handler": "aiChatApi",
      "modelName": "GetAiSessionRequest"
    },
    {
      "id": "DeleteAiSession",
      "method": "DELETE",
      "path": "/ai/sessions/{sessionId}",
      "handler": "aiChatApi",
      "modelName": "DeleteAiSessionRequest"
    },
    {
      "id": "StarAiSession",
      "method": "PUT",
      "path": "/ai/sessions/{sessionId}/star",
      "handler": "aiChatApi",
      "modelName": "StarAiSessionRequest"
    },
    {
      "id": "UpdateAiSession",
      "method": "PUT",
      "path": "/ai/sessions/{sessionId}",
      "handler": "aiChatApi",
      "modelName": "UpdateAiSessionRequest"
    },
    {
      "id": "GenerateAiSessionTitle",
      "method": "POST",
      "path": "/ai/sessions/{sessionId}/title",
      "handler": "aiChatApi",
      "modelName": "GenerateAiSessionTitleRequest"
    },
    {
      "id": "GetAiCompactedRanges",
      "method": "GET",
      "path": "/ai/sessions/{sessionId}/compacted",
      "handler": "aiChatApi",
      "modelName": "GetAiCompactedRangesRequest"
    },
    {
      "id": "SaveAiCompactedRange",
      "method": "POST",
      "path": "/ai/sessions/{sessionId}/compacted",
      "handler": "aiChatApi",
      "modelName": "SaveAiCompactedRangeRequest"
    },
    {
      "id": "SaveCompactedRange",
      "method": "POST",
      "path": "/ai-chat/sessions/{sessionId}/compacted",
      "handler": "aiChatApi",
      "modelName": "SaveCompactedRangeRequest"
    }
  ],
  "chatInvoke": [
    {
      "id": "ChatInvoke",
      "method": "POST",
      "path": "/chat/invoke",
      "handler": "chatInvoke",
      "modelName": "ChatInvokeRequest"
    }
  ],
  "aiSkillsApi": [
    {
      "id": "ListSkills",
      "method": "GET",
      "path": "/ai/skills",
      "handler": "aiSkillsApi",
      "modelName": "ListSkillsRequest"
    },
    {
      "id": "GetSkill",
      "method": "GET",
      "path": "/ai/skills/{name}",
      "handler": "aiSkillsApi",
      "modelName": "GetSkillRequest"
    },
    {
      "id": "CreateSkill",
      "method": "POST",
      "path": "/ai/skills",
      "handler": "aiSkillsApi",
      "modelName": "CreateSkillRequest"
    },
    {
      "id": "UpdateSkill",
      "method": "PUT",
      "path": "/ai/skills/{name}",
      "handler": "aiSkillsApi",
      "modelName": "UpdateSkillRequest"
    },
    {
      "id": "DeleteSkill",
      "method": "DELETE",
      "path": "/ai/skills/{name}",
      "handler": "aiSkillsApi",
      "modelName": "DeleteSkillRequest"
    }
  ],
  "aiCommandsApi": [
    {
      "id": "ListCommands",
      "method": "GET",
      "path": "/ai/commands",
      "handler": "aiCommandsApi",
      "modelName": "ListCommandsRequest"
    },
    {
      "id": "GetCommand",
      "method": "GET",
      "path": "/ai/commands/{name}",
      "handler": "aiCommandsApi",
      "modelName": "GetCommandRequest"
    },
    {
      "id": "CreateCommand",
      "method": "POST",
      "path": "/ai/commands",
      "handler": "aiCommandsApi",
      "modelName": "CreateCommandRequest"
    },
    {
      "id": "UpdateCommand",
      "method": "PUT",
      "path": "/ai/commands/{name}",
      "handler": "aiCommandsApi",
      "modelName": "UpdateCommandRequest"
    },
    {
      "id": "DeleteCommand",
      "method": "DELETE",
      "path": "/ai/commands/{name}",
      "handler": "aiCommandsApi",
      "modelName": "DeleteCommandRequest"
    }
  ],
  "aiMemoryApi": [
    {
      "id": "GetMemory",
      "method": "GET",
      "path": "/ai/memory",
      "handler": "aiMemoryApi",
      "modelName": "GetMemoryRequest"
    },
    {
      "id": "UpdateMemory",
      "method": "PUT",
      "path": "/ai/memory",
      "handler": "aiMemoryApi",
      "modelName": "UpdateMemoryRequest"
    }
  ],
  "lineageApi": [
    {
      "id": "GetLineageTrace",
      "method": "GET",
      "path": "/databases/{database}/tables/{table}/lineage/trace",
      "handler": "lineageApi",
      "modelName": "GetLineageTraceRequest"
    },
    {
      "id": "GetLineageImpact",
      "method": "GET",
      "path": "/databases/{database}/tables/{table}/lineage/impact",
      "handler": "lineageApi",
      "modelName": "GetLineageImpactRequest"
    },
    {
      "id": "CascadePreview",
      "method": "POST",
      "path": "/databases/{database}/tables/{table}/lineage/cascade-preview",
      "handler": "lineageApi",
      "modelName": "CascadePreviewRequest"
    },
    {
      "id": "CascadeExecute",
      "method": "POST",
      "path": "/databases/{database}/tables/{table}/lineage/cascade-execute",
      "handler": "lineageApi",
      "modelName": "CascadeExecuteRequest"
    }
  ],
  "eventsApi": [
    {
      "id": "ListActivityEvents",
      "method": "GET",
      "path": "/events",
      "handler": "eventsApi",
      "modelName": "ListActivityEventsRequest"
    },
    {
      "id": "GetActivityEvent",
      "method": "GET",
      "path": "/events/{eventId}",
      "handler": "eventsApi",
      "modelName": "GetActivityEventRequest"
    }
  ]
};

/**
 * Get route key for API Gateway (e.g., "GET /tables/{database}/{table}")
 */
export function getRouteKey(route: RouteDefinition): string {
  return `${route.method} ${route.path}`;
}

/**
 * Get all routes for a specific handler
 */
export function getRoutesByHandler(handler: string): RouteDefinition[] {
  return ROUTES.filter(r => r.handler === handler);
}

/**
 * Find route by path pattern
 */
export function findRoute(method: string, path: string): RouteDefinition | undefined {
  return ROUTES.find(r => r.method === method && r.path === path);
}

/**
 * Get unique handler names
 */
export function getHandlerNames(): string[] {
  return [...new Set(ROUTES.map(r => r.handler))];
}
